### ISSUE TITLE
/introduction/challenges.html - why lead with the negative spin?

### ISSUE THREAD

**Issue by tombaker** [naca-data-shapes/naca-data-shapes.github.io#6]
No quarrel with the content, but in the spirit of issue #5 , I suspect this entire discussion could be reduced to three or four sentences of on the "main-sequence" page with embedded links to "further information" pages.

It's true that many people have a negative image of RDF, but if we address this image in the main sequence of pages we only draw the attention of to RDF per se, whereas I suspect we will hold their attention better if we keep the attention on the general approach which (I hope) we will be able to summarize in an elevator pitch that does not use the acronym "RDF".

**Comment by andrawaag** [comment]
Feel free to rewrite it bluntly. Everything in the book are mere placeholders or ipsum lorem texts and can be treated as such.

The first edition was a demonstration of what executable book can do. Now that we have adopted this infrastructure and have set up a github repo to built it we can focus on content. 

You can add a preferred structure as folder in the GitHub repo and add new chapters and paragraphs as markdown files in those folders.

**Comment by tombaker** [comment]
@andrawaag - Thank you - very clear!

To summarize:
1. I will rewrite bluntly, but if I have any doubt, then instead of just deleting text, I will make free use of ~~strike-through~~.
2. I will make changes on a branch then, when enough change requests have accumulated, will submit a pull request.
3. Where I see a need to move technical detail off to the side, I will create a file outside of the TOC configuration and link to it.

**Comment by tombaker** [comment]
Closing as completed.
